[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
installCommand= "yarn install"
buildCommand= "yarn build"
startCommand = "medusa migrations run && medusa start"
healthcheckPath = "/health"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10