[build]
builder = "NIXPACKS"
buildCommand = "yarn run build"

[deploy]
numReplicas = 1
startCommand = "medusa migrations run && medusa start"
healthcheckPath = "/health"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10